baseURL = "https://qiti.iqc.uwaterloo.ca/"
languageCode = "en-us"
title = "QUANTUM INFORMATION WITH TRAPPED IONS"
subtitle = "University of Waterloo"
theme = "ananke"
#SectionPagesMenu = "mainmenu" #comment
[pagination]
  pagerSize = 15 # this is set low for demonstrating with dummy content. Set to a higher number. How many news items shown in one page.
summaryLength = 50

[Params]
background_color_class = "bg-gray"
featured_image = "images/header/ion_addressing_linear_bg_sub.gif"
homeList = ["news", "publications"]
favicon = "images/favicon.ico"
custom_css = ["css/myStyle.css"]

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[menu]

 [[menu.mainmenu]]
    identifier = "Members"
    name = "Members"
    title = "Members"
    url = "/members/"
    weight = 2

  [[menu.mainmenu]]
    identifier = "Group"
    name = "Group"
    title = "Group"
    url = "/group/"
    parent = "Members"
    weight = 1

  [[menu.mainmenu]]
    identifier = "Publications"
    name = "Publications"
    title = "Publications"
    url = "/publications/"
    weight = 3

 [[menu.mainmenu]]
    identifier = "Research"
    name = "Research"
    title = "Publication"
    url = "/research/"
    #parent = "Publications"
    weight = 1

 [[menu.mainmenu]]
    identifier = "News"
    name = "News"
    title = "News"
    url = "/news/"
    weight = 4
